services:
  ollama:
    image: ollama/ollama:0.32.2
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog:/home/mailhog
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog

volumes:
  ollama_data:
  mailhog:
